
  hosts: localhost
  gather_facts: false
  
  tasks:
    - name: Pull image
      community.docker.docker_image_pull:
        name: bagisto
        tag: 2.3.6

    - name: Start container
      community.docker.docker_container:
        cleanup: true
        command: python --version
        detach: false
        image: bagisto:2.3.6
        name: ecommerce-website
        output_logs: true

    - name: Show output
      ansible.builtin.debug:
        msg: "{{ output.container.Output }}"
